/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("org.eazyportal.plugin.portal")
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-validation")

}
