/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

dependencies {
    api("org.springframework.boot:spring-boot-starter-data-mongodb")
}
