eazyportal:
  file-handler:
    local:
      save-path: documents

spring:
  data:
    mongodb:
      host: localhost
      port: 27917
      database: documentStore
      username: documentStore
      password: DocumentStoreAdmin

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
